<?php
//
// Copyright (C) 2006-2009, Stephen Joyce, stephen@physics.unc.edu
//
// Released under the GPL license, 10/2006. Please see accompanying README.
//
 if (isset($_REQUEST['server']))
	$server = $_REQUEST['server'];
 else
        $server = "";
?>
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<head>
<title>Details for AFS fileserver <?php print "$server";?></title>
<META HTTP-EQUIV="Refresh" CONTENT="600; URL=detail.php?server=<?php print "$server";?>">
<!-- phpafsfree
Copyright (C) 2006-2009, Stephen Joyce, stephen@physics.unc.edu
-->
</head>

<body bgcolor="lightgrey">
 <table>
  <tr><td>
   <!-- graphic -->
   <img src="servers/<?php print "$server" ?>.php">
  </td><td valign="bottom">
   <!-- details -->
    <pre><?php
	if (!$fh = popen ("./partinfo.pl -ctT20,90 $server", "r")) {
        	echo ("Could not fork partinfo.pl");
	}
	while (!feof($fh)) {
		$line = fgets ($fh, 255);
		echo ("$line");
	}
	pclose($fh);
	print "\n\n\n";
	if (file_exists("notes/$server.txt")) {
		include("notes/$server.txt");
	} else {
		print "No other details available for $server.</br>";
		print "Details may be added in notes/$server.txt</br>";
	}
	?>
    </pre>
  </td></tr>
 </table>
<p align=right><small><i>This page generated by <a href="http://www.physics.unc.edu/~stephen/phpafsfree">phpafsfree</a>. Copyright (C) 2006-2009, Stephen Joyce.</i></small></p>
</body>
