<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<head>
<title>phpafsfree - AFS Fileserver Disk Utilization Grapher</title>
<META HTTP-EQUIV="Refresh" CONTENT="600; URL=index.php">
<!-- phpafsfree
Copyright (C) 2006-2016, Stephen Joyce
-->
<script type="text/javascript" src="lightbox/prototype.js"></script>
<script type="text/javascript" src="lightbox/scriptaculous.js?load=effects,builder"></script>
<script type="text/javascript" src="lightbox/lightbox.js"></script>
<link rel="stylesheet" href="lightbox/lightbox.css" type="text/css" media="screen" />
</head>
<body bgcolor="lightgrey">
<center><h3>phpafsfree - AFS Fileserver Disk Utilization Grapher</hd></center>

<?php
// change to false if you don't like lightbox images.
$uselightbox=true;

if (!$fh=popen ("/bin/ls servers","r")) {
	echo ("Could not fork ls");
}
$incr=0;
while (!feof($fh)) {
	$line=fgets($fh);
	$line=str_replace("\n","",$line);
	if ($line == "") continue;
	$incr++;
	$files[$incr]=$line;
	$line=str_replace(".php","",$line);
	$servers[$incr]=$line;
	//print "$line<br>";
}
fclose($fh);

// default array ordering is alphabetic.
// if you want to reorder your array for artificial means, do it here.
#$servers[1]="afsfs1.domain.dom";

print "<center><small>Click on any image to enlarge.<br>Click any server name for more detailed information.</small></center>";
print "<br>";
print "<center><table border=0 cellpadding=4>\n";

$numcolumns=5;
$column=1;
print "<tr>\n";
for ($incr=1;$incr<=sizeof($servers);$incr++) {
	print "<td align=\"center\"><a href=\"servers/$servers[$incr].php\"";
	if ($uselightbox == "true" ) {
	  print "rel=\"lightbox[afsserver]\"";
	}
	print "><img src=\"servers/$servers[$incr].php\" height=\"300\" border=\"0\"></a><br><b><a href=\"detail.php?server=$servers[$incr]\" target=\"_new\">$servers[$incr]</a></b></td>\n";
	$column++;
	if ($column==$numcolumns+1) {
		print "</tr><tr><td colspan=\"$numcolumns\" height=\"20\"></td>\n";
		print "</tr><tr>\n";
		$column=1;
	}
}
while($column<=$numcolumns) {
	print "<td></td>";
	$column++;
}

?>
</table>
</center>
<p align=right><small><i>This page generated by <a href="http://github.com/stephen10/phpafsfree">phpafsfree</a>. Copyright (C) 2006-2016, Stephen Joyce.</i></small></p>
</body>
